const SECRET="princessmiftah",S=document.getElementById("screen"),M=document.getElementById("modal"),MT=document.getElementById("mt"),MX=document.getElementById("mx"),MI=document.getElementById("mi"),MB=document.getElementById("mb");for(let i=0;i<22;i++){let p=document.createElement("i");p.className="petal";p.textContent=["🌸","✿","·"][i%3];p.style.left=Math.random()*100+"%";p.style.animationDuration=7+Math.random()*9+"s";p.style.animationDelay=-Math.random()*12+"s";document.getElementById("petals").appendChild(p)}
let tries=0;function unlock(){if(document.getElementById("secret").value.toLowerCase().replace(/\s/g,"")===SECRET){document.getElementById("lock").remove();document.getElementById("world").classList.remove("hiddenWorld")}else{let a=["Nope 😌 Even the rabbits are judging you.","Miffy… the teddies are concerned. 😂","Wrong secret word. Princess privileges denied.","Ask Bushra before the dinos lose faith in you. 🦕"];document.getElementById("lockmsg").textContent=a[Math.min(tries++,3)]}}document.getElementById("unlock").onclick=unlock;document.getElementById("secret").onkeydown=e=>{if(e.key==="Enter")unlock()};
const Q=[
["Where did we first travel together?",["Goa 🌴","Perth 🐨","Bangalore 🏙️","The land of endless arguments 😌"],0,[["Miffy?! 😭","Were you even there? Think harder."],["Wrong continent 😂","Lovely trip. Wrong memory."],["Home base does not count 😌","Nice attempt. Try again."],["Tempting 😂","Emotionally plausible. Geographically incorrect."]]],
["Who behaves like a spoiled princess?",["Bushra 👑","Miftah 👸"],1,[["EXCUSE ME?? 🤨","Birthday boy privilege does NOT include rewriting history. Think again, Princess Miftah. 👸"]]],
["One thing Miftah cannot stay without?",["Bushra ❤️","Games 🎮","Food 🍜","Sleep 😴"],1,[["Awwwww ❤️","Very romantic. Very sweet. Completely incorrect. 🎮"],["Nope 😌","The gaming teddies know the truth."],["Who are you? 🤨","Food over games? What have you done with my husband?"],["Absolutely not 😂","You have sacrificed sleep FOR games."]]],
["Who makes up after each fight?",["Miftah 😇","Bushra 😌"],1,[["HAHAHAHAHAHA 😂","Sorry. The rabbits needed a minute after that one."]]],
["Who starts every fight?",["Bushra 😇","Miftah 🔥"],1,[["⚠️ DANGEROUS ANSWER","You still have time to reconsider this decision, Miffy."]]],
["Who loves more?",["Miftah ❤️","Bushra ❤️❤️"],1,[["Citation needed 📚","Source: Miftah et al., Trust Me Bro (2026). Peer review rejected."]]],
["Who swiped first?",["Bushra 👀","Miftah 👉"],1,[["Historical revisionism 👀","The archives—and the tiny dinos—remember, Miffy."]]]
],C=[["Correct! 🌴","The adventure continues!"],["👑 TRUTH ACCEPTED 👑","Princess Miftah has acknowledged his title."],["Correct! 🎮","The gaming teddies celebrate your honesty."],["Peace restored 😌","Correct. Somebody has to make up."],["Self-awareness unlocked 😂","The rabbits appreciate your honesty."],["Obviously. 💗","Bushra's answer key remains undefeated."],["The archives approve ✨","And look where that swipe got you…"]];
let n=0,wrong=Array(7).fill(0),cb=null;function pop(t,x,good=false,next=null){MT.textContent=t;MX.textContent=x;MI.textContent=good?"✨":"😂";MB.textContent=good?"Continue →":"Fine, let me try again 🙄";M.classList.remove("hide");cb=next}MB.onclick=()=>{M.classList.add("hide");let f=cb;cb=null;if(f)f()};
function draw(){let q=Q[n];S.innerHTML=`<div class="progress">${Q.map((_,i)=>`<i class="dot ${i<n?"done":""}"></i>`).join("")}</div><div class="qno">QUESTION ${n+1} OF 7</div><div class="big">${["🧳","👑","🎮","🌷","🔥","💗","✨"][n]}</div><h2>${q[0]}</h2><div class="answers">${q[1].map((o,i)=>`<button class="answer" data-i="${i}">${o}</button>`).join("")}</div><small>Choose wisely. Bushra controls the answer key. 😌</small>`;S.querySelectorAll(".answer").forEach(b=>b.onclick=()=>pick(+b.dataset.i))}
function pick(i){let q=Q[n];if(i===q[2]){let c=C[n];pop(c[0],c[1],true,()=>{n++;n<7?draw():door()});return}let w=q[3][i]||["Nope 😂","The tiny animals disagree. Try again."];if(n===1&&i===0){let e=[["EXCUSE ME?? 🤨","Birthday boy privilege does NOT include rewriting history. Think again, Princess Miftah. 👸"],["YOU CLICKED BUSHRA AGAIN?! 😭","The confidence is concerning."],["Miftah. My patience has left the chat. 🙂","There are TWO options. Click your own name, Princess."],["STILL?! 😂","Even the dinosaurs are judging you now."]];w=e[Math.min(wrong[n]++,3)]}pop(w[0],w[1])}
document.getElementById("start").onclick=draw;function door(){S.innerHTML=`<div class="big">🚪🌸✨</div><h2>The final door has opened…</h2><p>Turns out one little swipe led to quite an adventure.</p><button id="go" class="btn">Let's see… →</button>`;document.getElementById("go").onclick=mem}function mem(){S.innerHTML=`<div class="eyebrow">A FEW CHAPTERS LATER…</div><div class="big">🐰🧸🦕</div><h2>Look at all the little adventures that followed.</h2><div class="memorygrid"><div class="memory">🌴 First adventures</div><div class="memory">🚤 New places</div><div class="memory">🐨 Silly moments</div><div class="memory">🚲 Exploring together</div><div class="memory">🎮 Lots of #me time 😏</div><div class="memory">❤️ Same team, always</div></div><button id="last" class="btn">One last thing… ❤️</button>`;document.getElementById("last").onclick=finale}function finale(){document.getElementById("world").classList.add("party");S.innerHTML=`<div class="big">🎂🌸✨</div><div class="letter"><h2>Happy Birthday Miftah! ❤️</h2><p>Stay happy and blessed with lots of happiness, health and your <strong>#me time :P</strong></p><p><em>— Bushra ❤️</em></p></div><div class="achievement"><strong>🏆 ACHIEVEMENT UNLOCKED</strong><p>Another year of <b>Games</b>, <b>Bushra</b> & being a <b>spoiled princess</b>. 👸🎮</p></div>`}